### ISSUE TITLE
Будет ли поддержка ESP32-2432S024?

### ISSUE THREAD

**Issue by Asmodeux2** [valerio-vaccaro/HAN#5]
Будет ли поддержка ESP32-2432S024? Будет ли готовые bin файлы для заливки на плату или только самостоятельная сборка?

**Comment by toreone** [comment]
Hi Valerio, I think you have to say what is the procedure to reset the nerdminer, for example in case you have to change the password of wifi.
I tried to write that procedure:

to reset the esp32 plus (only chrome)
1) https://espressif.github.io/esptool-js/
connect via serial 115200 to your nerdminer
select your board
press reset and wait

to flash esp32
https://valerio-vaccaro.github.io/diyflasher/
go to your wifi settings and search nerdminerAP
password wifi default: MineYourCoins
from chrome go to page http://192.168.4.1/ for setting your nerdminer

**Comment by Asmodeux2** [comment]
Support true = https://valerio-vaccaro.github.io/diyflasher/
